---
name: Release Bmeme GCP Image Builder container image
on:
  push:
    branches:
      - "main"

env:
  registry: docker.io
  repository: bmeme/gcp-image-builder

jobs:

  build:
    name: Build and test Bmeme GCP Image Builder container image using Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set tag
        id: vars
        run: echo "tag=$(cat ./Dockerfile | grep com.bmeme.project.version | awk -F\' '{print $2}')" >> $GITHUB_OUTPUT
      -
        name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: "linux/arm64,linux/amd64"
          tags: |
            ${{ env.registry }}/${{ env.repository }}:${{ steps.vars.outputs.tag }}
            ${{ env.registry }}/${{ env.repository }}:latest